---
# Role tasks

- block:
    - name: Search Check_MK agent local dir
      shell: >-
        /usr/bin/check_mk_agent | grep '[L]ocalDirectory' | awk {'print $2'}
      args:
        warn: no
      changed_when: no
      failed_when: >-
        check_mk_agent_jstat_search_local_dir_result.stdout_lines
        | length == 0
      register: check_mk_agent_jstat_search_local_dir_result

    - name: Setup directory for Check_MK agent local checks
      file:
        path: >-
          {{ check_mk_agent_jstat_local_dir
             + "/"
             + check_mk_agent_jstat_seconds | string }}
        state: directory
        owner: root
        group: root
        mode: 0644

    - name: Setup Check_MK agent jstat script
      template:
        src: check-jstat.j2
        dest: >-
          {{ check_mk_agent_jstat_local_dir
             + "/"
             + check_mk_agent_jstat_seconds | string
             + "/"
             + check_mk_agent_jstat_file }}
        owner: root
        group: root
        mode: 0755

  vars:
    check_mk_agent_jstat_local_dir: >-
      {{ check_mk_agent_jstat_search_local_dir_result.stdout_lines[0] }}
  tags:
    - role::check_mk_agent_jstat
