---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Search Check_MK agent local dir
      shell: >-
        /usr/bin/check_mk_agent | grep '[L]ocalDirectory' | awk {'print $2'}
      args:
        warn: no
      changed_when: no
      register: search_local_dir_result

    - name: Test jstat check
      command: >-
        {{ search_local_dir_result.stdout_lines[0]
           + "/"
           + check_mk_agent_jstat_seconds | string
           + "/"
           + check_mk_agent_jstat_file }}
      changed_when: no
      register: check_result

    - name: Assert check output is ok
      assert:
        that: check_result.stdout_lines | length == 0
  vars:
    ansible_python_interpreter: >-
      {{ (inventory_hostname in groups.molecule_hosts_centos_7)
         | ternary("/usr/bin/python", "/usr/bin/python3") }}
